// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6rcFcLEp4i6EqgaVE-Xb7mvxnb3O7ag',
    appId: '1:838227296286:web:584ee677454b6c7d7b6e0f',
    messagingSenderId: '838227296286',
    projectId: 'fridgex-93c26',
    authDomain: 'fridgex-93c26.firebaseapp.com',
    storageBucket: 'fridgex-93c26.firebasestorage.app',
    measurementId: 'G-S6GND3KWLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTC5NHBiezJNINgr5nsDCLf6Npm2I8PDE',
    appId: '1:838227296286:android:00e6943170a2e61f7b6e0f',
    messagingSenderId: '838227296286',
    projectId: 'fridgex-93c26',
    storageBucket: 'fridgex-93c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlluoGKu5sVOfDFrSUxgadoquWMg5ZGoc',
    appId: '1:838227296286:ios:9dd9034bcf2750737b6e0f',
    messagingSenderId: '838227296286',
    projectId: 'fridgex-93c26',
    storageBucket: 'fridgex-93c26.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlluoGKu5sVOfDFrSUxgadoquWMg5ZGoc',
    appId: '1:838227296286:ios:9dd9034bcf2750737b6e0f',
    messagingSenderId: '838227296286',
    projectId: 'fridgex-93c26',
    storageBucket: 'fridgex-93c26.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6rcFcLEp4i6EqgaVE-Xb7mvxnb3O7ag',
    appId: '1:838227296286:web:4d404e17041c19717b6e0f',
    messagingSenderId: '838227296286',
    projectId: 'fridgex-93c26',
    authDomain: 'fridgex-93c26.firebaseapp.com',
    storageBucket: 'fridgex-93c26.firebasestorage.app',
    measurementId: 'G-B1LBT198P6',
  );

}